version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    environment:
      - TZ=America/Guatemala
    command:
      - "--api.dashboard=false"                    # Habilita la UI de Traefik
      - "--api.insecure=true"
      - "--providers.docker=true"                 # Habilita la detección automática de contenedores Docker
      - "--providers.docker.exposedbydefault=false" # Evita exponer contenedores por defecto
      - "--entrypoints.web.address=:80"           # Define el puerto 80 como punto de entrada
      - "--entrypoints.websecure.address=:443" # new
      - "--certificatesresolvers.lets-encrypt.acme.tlschallenge=true" # new
      - "--certificatesresolvers.lets-encrypt.acme.email=eddy9062@gmail.com" # new
      - "--certificatesresolvers.lets-encrypt.acme.storage=/letsencrypt/acme.json" # new
    ports:
      - 80:80    # Expone el puerto HTTP
      - 443:443
      - 8080:8080 # Interfaz web de Traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # Permite a Traefik comunicarse con Docker
      - /root/docker/volumes/traefik/letsencrypt:/letsencrypt/
      - /root/docker/logs/traefik/:/traefik/logs/
    labels:  
      - "traefik.enable=true"
       # Redireccionamiento de HTTP a HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    networks:
      - proxy

networks:
  proxy:
    external: true  # Usa la red creada manualmente
